# Frontend - app.webotonom.de
server {
    listen 80;
    server_name app.webotonom.de;

    root /www/motorworld-app;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
}
